import json


names_of_programs = [
    'B.S., Accountancy, Information Systems', 
    'B.S., Accountancy, Professional Accountancy', 
    'B.A., Africana Studies, African and African-American Social Sciences', 
    'B.A., Africana Studies, African and African-American Humanities and Cultural Studies', 
    'B.A., Africana Studies, African-American Urban Education', 
    'B.A., Anthropology', 
    'B.A., Art', 
    'B.A., Asian American Studies, Standard Major', 
    'B.A., Asian American Studies, Double Major', 
    'B.S., Athletic Training', 
    'B.S., Biochemistry', 
    'B.A., Biology', 
    'B.S., Biology, Cell and Molecular Biology', 
    'B.S., Biology, Ecology and Evolutionary Biology', 
    'B.S., Biology, Microbiology', 
    'B.S., Biology, Biotechnology - Medical Technology', 
    'B.S., Biology, Marine Biology', 
    'B.S., Business Administration, Business Analytics', 
    'B.S., Business Administration, Business Law', 
    'B.S., Business Administration, Financial Analysis', 
    'B.S., Business Administration, Financial Planning', 
    'B.S., Business Administration, Global Supply Chain Management', 
    'B.S., Business Administration, Management', 
    'B.S., Business Administration, Marketing', 
    'B.S., Business Administration, Real Estate', 
    'B.S., Business Administration, Risk Management and Insurance', 
    'B.S., Business Administration, Systems and Operations Management', 
    'B.A., Central American Studies, Standard Major', 
    'B.A., Central American Studies, Double Major', 
    'B.A., Chemistry', 
    'B.S., Chemistry', 
    'B.A., Chicano and Chicana Studies, Single Major', 
    'B.A., Chicano and Chicana Studies, Double Major', 
    'B.A., Chicano and Chicana Studies, Chicana - o Studies Social Science Subject Matter Waiver Program', 
    'B.A., Child and Adolescent Development, Applied Developmental Science', 
    'B.A., Child and Adolescent Development, Early Childhood Development', 
    'B.A., Cinema and Television Arts, Entertainment Media Management', 
    'B.A., Cinema and Television Arts, Film Production', 
    'B.A., Cinema and Television Arts, Media Theory and Criticism', 
    'B.A., Cinema and Television Arts, Emerging Media Production', 
    'B.A., Cinema and Television Arts, Screenwriting', 
    'B.A., Cinema and Television Arts, Television Production', 
    'B.S., Civil Engineering', 
    'B.A., Communication Studies', 
    'B.A., Communicative Disorders', 
    'B.S., Computer Engineering', 
    'B.S., Computer Information Technology', 
    'B.S., Computer Science', 
    'B.S., Construction Management', 
    'B.A., Criminology and Justice Studies', 
    'B.A., Deaf Studies', 
    'B.A., Economics', 
    'B.S., Electrical Engineering', 
    'B.S., Engineering Management Technology', 
    'B.A., English, Literature', 
    'B.A., English, Creative Writing', 
    'B.A., English, Subject Matter Program for the Single Subject Credential', 
    'B.A., English, Four-Year Integrated (FYI) English Subject Matter Program for the Single Subject Credential (DEAD)', 
    'B.A., English, Junior-Year Integrated (JYI) English Subject Matter Program for the Single Subject Credential (DEAD)', 
    'B.A., English, Honors', 
    'B.S., Environmental and Occupational Health, Industrial Hygiene', 
    'B.S., Environmental and Occupational Health', 
    'B.A., Environmental Science', 
    'B.S., Family and Consumer Sciences, Apparel Design and Merchandising', 
    'B.S., Family and Consumer Sciences, Consumer Affairs', 
    'B.S., Family and Consumer Sciences, Family and Consumer Sciences Education', 
    'B.S., Family and Consumer Sciences, Family Studies', 
    'B.A., Gender and Women’s Studies, Double Major (DEAD)', 
    'B.A., Gender and Women’s Studies', 
    'B.S., Geographic Information Science', 
    'B.S., Geography and Environmental Studies', 
    'B.S., Geology, Geology', 
    'B.S., Geology, Geophysics', 
    'B.S., Health Administration', 
    'B.A., History', 
    'B.A., History, Four-Year Integrated (FYI) History Subject Matter Program for the Single Subject Credential (DEAD)', 
    'B.A., History, Junior-Year Integrated (JYI) History Subject Matter Program for the Single Subject Credential (DEAD)', 
    'B.S., Information Systems, Business Systems', 
    'B.S., Information Systems, Software Technology', 
    'B.S., Information Systems, Computer Information Technology', 
    'B.S., Information Systems, Health Systems', 
    'B.A., Interdisciplinary Studies', 
    'B.S., Interior Design', 
    'B.A., Jewish Studies', 
    'B.A., Journalism', 
    'B.A., Journalism, Broadcast', 
    'B.A., Journalism, Public Relations', 
    'B.S., Kinesiology, Exercise Science', 
    'B.S., Kinesiology, Dance', 
    'B.S., Kinesiology, Sport Studies', 
    'B.S., Kinesiology, Applied Fitness and Active Lifestyle Development', 
    'B.S., Kinesiology, Physical Education', 
    'B.A., Languages and Cultures, Armenian', 
    'B.A., Languages and Cultures, French', 
    'B.A., Languages and Cultures, Italian', 
    'B.A., Languages and Cultures, Japanese', 
    'B.A., Liberal Studies, Pre-Credential Program (DEAD)', 
    'B.A., Liberal Studies, Integrated Teacher Education Program (ITEP) Junior (DEAD)', 
    'B.A., Liberal Studies, Integrated Teacher Education Program (ITEP) Freshman (DEAD)', 
    'B.A., Linguistics', 
    'B.S., Manufacturing Systems Engineering', 
    'B.A., Mathematics, Four-Year Integrated (FYI) Mathematics Subject Matter Program for the Single Subject Credential (DEAD)', 
    'B.A., Mathematics, Junior-Year Integrated (JYI) Mathematics Subject Matter Program for the Single Subject Credential (DEAD)', 
    'B.A., Mathematics, General', 
    'B.A., Mathematics, Secondary Teaching', 
    'B.S., Mathematics, Mathematics', 
    'B.S., Mathematics, Statistics', 
    'B.S., Mathematics, Applied Mathematical Sciences', 
    'B.S., Mechanical Engineering', 
    'B.A., Music, Breadth Studies', 
    'B.A., Music, Music Industry Studies', 
    'B.A., Music, Music Education', 
    'B.A., Music, Music Therapy', 
    'B.M., Music, Jazz Studies', 
    'B.M., Music, Composition - Commercial and Media Writing', 
    'B.M., Music, Vocal Arts', 
    'B.M., Music, Keyboard', 
    'B.M., Music, Percussion', 
    'B.M., Music, Winds', 
    'B.M., Music, Strings', 
    'B.S., Nursing, Accelerated (DEAD)', 
    'B.S., Nursing, RN to BSN', 
    'B.S., Nutrition, Dietetics and Food Science, Nutrition and Dietetics', 
    'B.S., Nutrition, Dietetics and Food Science, Food Science', 
    'B.A., Philosophy, Double Major (DEAD)', 
    'B.A., Philosophy', 
    'B.A., Physics', 
    'B.S., Physics, Physics', 
    'B.S., Physics, Astrophysics', 
    'B.A., Political Science, Politics and Government', 
    'B.A., Political Science, Public Policy and Management', 
    'B.A., Political Science, Law and Society', 
    'B.A., Psychology', 
    'B.A., Psychology, Honors (DEAD)', 
    'B.S., Public Health', 
    'B.A., Public Sector Management', 
    'B.S., Radiologic Sciences', 
    'B.A., Religious Studies, Double Major (DEAD)', 
    'B.A., Religious Studies', 
    'B.A., Sociology', 
    'B.A., Spanish, Hispanic Linguistics', 
    'B.A., Spanish, Translation and Interpretation', 
    'B.A., Spanish, Literature', 
    'B.A., Spanish, Language and Culture', 
    'B.A., Theatre', 
    'B.S., Tourism, Hospitality, and Recreation Management', 
    'B.A., Urban Studies and Planning']

# names_of_programs = [
#     'B.S., Accountancy, Information Systems', 
#     'B.S., Accountancy, Professional Accountancy', 
#     'B.A., Africana Studies, African and African-American Social Sciences']

for name_of_program in names_of_programs:
    if not name_of_program.__contains__("(DEAD)"):
        with open(f"../../code-assets/backend/json_majors/{name_of_program.replace('/', ' - ').replace(':', ',')}.json") as curr_major:
            curr_major_blob = json.load(curr_major)
            major_string = curr_major_blob["prog-reqq-blob"]

            print(name_of_program + "------------------")
            print(major_string[major_string.find("General Education ("):major_string.find("Total")])
            curr_major_blob["general-education"] = major_string[major_string.find("General Education ("):major_string.find("Total")]
            json.dump(curr_major_blob, open(f"../../code-assets/backend/json_majors/{name_of_program.replace('/', ' - ').replace(':', ',')}.json", "w"), indent=4)
            print("\n\n\n")
    